## UniFlex Agent config file

config:
  name: "Global_Controller"
  info: 'agent hosts global controller'
  iface: 'lo'
  sub: "tcp://192.168.10.157:8990"
  pub: "tcp://192.168.10.157:8989"

broker:
  xpub: "tcp://192.168.10.157:8990"
  xsub: "tcp://192.168.10.157:8989"

control_applications:
  myController:
      file : channel_controller.py
      class_name : UniflexChannelController
      openAIGymController: True
      kwargs : {
            'availableChannels' : [1,5]
      }

modules:
  discovery:
        module : uniflex_app_discovery_pyre
        class_name : PyreDiscoveryMasterModule
        kwargs: {"iface":"lo",
                 "groupName":"uniflex_1234",
                 "sub":"tcp://192.168.10.157:8990",
                 "pub":"tcp://192.168.10.157:8989"
                }
