## UniFlex Agent config file

config:
  name: 'HC node'
  info: 'rrm multi scenario simulation'
  iface: 'lo'
  iface: 'lo'
  sub: "tcp://127.0.0.1:8990"
  pub: "tcp://127.0.0.1:8989"

control_applications:
  discovery:
      module : uniflex_app_discovery_pyre
      class_name : PyreDiscoverySlaveModule
      kwargs: {"iface":"lo", "groupName":"uniflex_1234"}

modules:
  simple:
      module : uniflex_module_simple
      class_name : SimpleModule4
      devices : ['phy0']
      kwargs : { "clients" : ["cc:cc:cc:cc:cc:21", "cc:cc:cc:cc:cc:22", "cc:cc:cc:cc:cc:23", "cc:cc:cc:cc:cc:24", "cc:cc:cc:cc:cc:25", "cc:cc:cc:cc:cc:26"],
        'neighbors' : [['aa:aa:aa:aa:aa:02', 'aa:aa:aa:aa:aa:01'], ['aa:aa:aa:aa:aa:02'], ['aa:aa:aa:aa:aa:01']],
        'myMAC' : 'aa:aa:aa:aa:aa:03',
        'simulation': {'channelSwitchingTime': 0, 'channelThroughputDefault':54000000, 'txBytesRandom':0, 'clientnum':2, 'clientconf': 'path-to-configfiles/3_112_AP3', 
        'mode': 'generator', # training or working or generator
        'numsClients': [5,2,3,2,2],
            #for generator
            'maxNumClients' : 100,
            'scenariosPerAPSetting': 60,
            'clientPrefix' : "cc:cc:cc:cc:03:",
            'scenarioBackup' : 'path-to-backup-files/AP3_scenarios.var'
        }}

